POST http://localhost:8080/accounts
Content-Type: application/json
Authorization: Basic manager:goodpassword

{
    "customer_id":4,
    "balance":20000,
    "available_balance":12000

}

######
POST http://localhost:8080/accounts
Content-Type: application/json
Authorization: Basic manager:goodpassword

{
    "customer_id":3,
    "balance":1000,
    "available_balance":500

}
#######
GET http://localhost:8080/accounts
Content-Type: application/json
Authorization: Basic user1:goodpassword

{
    "customer_id":3,
    "balance":20000,
    "available_balance":1500000.0

}

#######
#Create an account that should be deleted together with the user

POST http://localhost:8080/accounts
Content-Type: application/json
Authorization: Basic manager:goodpassword

{
    "customer_id":5,
    "balance":1000,
    "available_balance":500

}