#Logout
GET http://localhost:8080/logout

#####
GET http://localhost:8080/customers
Authorization: Basic manager:goodpassword

####
POST http://localhost:8080/customers
Content-Type: application/json
Authorization: Basic manager:goodpassword

{   
    "username":"kazuma",
    "password":"password" ,
    "full_name":"Satou Kazuma",
    "nric":"S7982834C", 
    "phone":"91251234", 
    "address":"Tokyo, Japan", 
    "authorities":"ROLE_USER",
    "active": true 
}

#####
#Delete Kazuma so that the account vanishes
#FOR TESTING ONLY - NOT A REQUIRED FUNCTION
DELETE  http://localhost:8080/customers/5